// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AssetManagement.Models;

public partial class Category
{
    public int Id { get; set; }

    public string CategoryName { get; set; }

    public int AccountId { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<Keyword> Keywords { get; set; } = new List<Keyword>();
}