// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AssetManagement.Models;

public partial class Transaction
{
    public int Id { get; set; }

    public DateTime Date { get; set; }

    public string Merchant { get; set; }

    public double OutgoingAmount { get; set; }

    public double IncomingAmount { get; set; }

    public int CategoryId { get; set; }

}